name: "beamsearch_ckpt2"
input_path: "/network/scratch/k/kusha.sareen/genPPO/data/gsm8k/test"
policy_model: "ReasoningMila/polIter_rho1bSft2_vineppo_GSM8K_ver_coeff_1e_1_from_vp_checkpoint" # edit ckpt
reward_model: "ReasoningMila/polIter_rho1bSft2_vineppo_GSM8K_ver_coeff_1e_1_from_vp_checkpoint"
device: "cuda"
beam_width: 4
max_depth: 20
beam_size: 32
top_k: 100
search_algorithm: "beamsearch"
use_async: true
download_dir: "/network/scratch/k/kusha.sareen/cache"
generation_temp: 0.7 # 0.35
verification_temp: 1.0
aggregator: "last" # min or sum or last
max_tokens: 512
verification_question: "\nIs the solution likely to result in the correct answer (Yes/No)?\n"
log_all_scores: true
output_path: "/home/mila/k/kusha.sareen/scratch/genPPO/outputs"
llm_as_judge: false
ppo: false
use_advantage: false
orm_avg: false
dataset: "gsm8k" # gsm8k or math
seed: 0
num_samples: -1