name: "bestofn_vineppo"
input_path: "/network/scratch/k/kusha.sareen/genPPO/data/gsm8k/test"
policy_model: "ReasoningMila/vineppo_baseline_ckpt" # ReasoningMila/vineppo_baseline_ckpt
reward_model: "ReasoningMila/vineppo_baseline_ckpt" # ReasoningMila/vineppo_baseline_ckpt
device: "cuda"
max_depth: 20
n: 3
top_k: 3
search_algorithm: "bestofn"
use_async: true
download_dir: "/network/scratch/k/kusha.sareen/cache"
generation_temp: 0 # 0.35 or 0.7
verification_temp: 1.0
aggregator: "last" # min or product or id
max_tokens: 1024
verification_question: "" # uses llm as judge instead
log_all_scores: false # should be false whenever only using orm
output_path: "/home/mila/k/kusha.sareen/scratch/genPPO/outputs"
llm_as_judge: true
ppo: false
use_advantage: false
orm_avg: false
dataset: "gsm8k" # gsm8k or math
seed: 0
num_samples: -1
id: ""