name: "bestofn_vineppo"
input_path: "/network/scratch/k/kusha.sareen/genPPO/data/gsm8k/test"
policy_model: "ReasoningMila/vineppo_baseline_ckpt" # ReasoningMila/vineppo_baseline_ckpt
reward_model: "ReasoningMila/vineppo_baseline_ckpt" # ReasoningMila/vineppo_baseline_ckpt
device: "cuda"
max_depth: 10
n: 90
top_k: 90
search_algorithm: "bestofn"
use_async: true
download_dir: "/network/scratch/k/kusha.sareen/cache"
generation_temp: 0.35 # 0.35
verification_temp: 0.35
aggregator: "last" # min or product or id
max_tokens: 512
verification_question: "" # uses llm as judge instead
log_all_scores: false
output_path: "/home/mila/k/kusha.sareen/scratch/genPPO/outputs"