name: "bestofn_math"
input_path: "/network/scratch/k/kusha.sareen/genPPO/data/math/test"
policy_model: "/home/mila/k/kusha.sareen/scratch/genPPO/clf_1" # edit ckpt
reward_model: "/home/mila/k/kusha.sareen/scratch/genPPO/clf_1"
device: "cuda"
max_depth: 20
n: 32
top_k: 32
search_algorithm: "bestofn"
use_async: true
download_dir: "/network/scratch/k/kusha.sareen/cache"
generation_temp: 0.7 # 0.35
verification_temp: 1.0
aggregator: "min" # min or sum or last
max_tokens: 2048
verification_question: "\nIs the solution likely to result in the correct answer (Yes/No)?\n"
log_all_scores: true
output_path: "/home/mila/k/kusha.sareen/scratch/genPPO/outputs/simple_test_box"
llm_as_judge: false
ppo: false
use_advantage: false
orm_avg: false
dataset: "math128" # gsm8k or math
seed: 0
num_samples: -1
id: ""